CREATE TABLE PROPERTIES (
    APPLICATION VARCHAR(100),
    PROFILE VARCHAR(20),
    LABEL VARCHAR(20),
    KEY VARCHAR(500),
    VALUE VARCHAR(500)
);
/
ALTER TABLE PROPERTIES
ADD CONSTRAINT PK_PROPERTIES PRIMARY KEY(APPLICATION, PROFILE, KEY);
/