spring:
  application:
    name: platepal-discovery-service
  profiles:
    active: jdbc
  config:
    import: "optional:configserver:http://localhost:7001/platepal-config-service"
  cloud:
    config:
      uri: http://localhost:7001/platepal-config-service
      label: jdbc

server:
  port: 7002
  servlet:
    context-path: /platepal-discovery-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:7002/platepal-discovery-service/eureka
  instance:
    prefer-ip-address: true